In [2]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn import svm
from sklearn import neighbors
from sklearn import tree
import random
import matplotlib.pyplot as plt
from sklearn import svm, datasets
from sklearn.metrics import roc_curve, auc  ###计算roc和auc
from sklearn import model_selection

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()
obj = load_iris()
print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [4]:
trainning_num=100
testing_num=50
X_train=[]
y_train=[]
X_test=[]
y_test=[]
total_train=[]
total_test=[]
order=[]
for a,b in zip(iris.data,iris.target):
    total_train.append(a)
    total_test.append(b)
# total_train,total_test = total_train[total_test != 2],total_test[total_test != 2]
for i in range(len(obj.data)):
    order.append(i)
random.shuffle(order)
for i in range(trainning_num):
    X_train.append(total_train[order[i]])
    y_train.append(total_test[order[i]])
for i in range(testing_num):
    i = trainning_num+i
    X_test.append(total_train[order[i]])
    y_test.append(total_test[order[i]])

X_train=np.array(X_train)
y_train=np.array(y_train)
X_test=np.array(X_test)
y_test=np.array(y_test)
for k in [X_train,y_train,X_test,y_test]:
#     k = np.array(k)
    print(k)


[[7.1 3.  5.9 2.1]
 [7.2 3.2 6.  1.8]
 [6.7 3.  5.  1.7]
 [5.1 3.5 1.4 0.3]
 [6.6 3.  4.4 1.4]
 [5.  3.5 1.6 0.6]
 [7.7 3.8 6.7 2.2]
 [5.5 3.5 1.3 0.2]
 [5.2 2.7 3.9 1.4]
 [7.9 3.8 6.4 2. ]
 [7.  3.2 4.7 1.4]
 [5.8 4.  1.2 0.2]
 [5.8 2.6 4.  1.2]
 [7.7 3.  6.1 2.3]
 [5.6 2.8 4.9 2. ]
 [6.2 3.4 5.4 2.3]
 [6.1 2.6 5.6 1.4]
 [5.7 2.8 4.1 1.3]
 [5.4 3.4 1.5 0.4]
 [6.3 2.5 4.9 1.5]
 [6.4 3.1 5.5 1.8]
 [5.6 3.  4.5 1.5]
 [6.  3.  4.8 1.8]
 [5.8 2.8 5.1 2.4]
 [5.7 4.4 1.5 0.4]
 [6.  2.2 4.  1. ]
 [5.5 2.4 3.8 1.1]
 [6.3 3.3 6.  2.5]
 [6.2 2.8 4.8 1.8]
 [5.  3.3 1.4 0.2]
 [6.9 3.2 5.7 2.3]
 [5.7 2.9 4.2 1.3]
 [6.9 3.1 5.4 2.1]
 [6.3 2.8 5.1 1.5]
 [6.9 3.1 4.9 1.5]
 [7.7 2.6 6.9 2.3]
 [6.4 2.7 5.3 1.9]
 [5.5 2.4 3.7 1. ]
 [6.7 3.  5.2 2.3]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [6.3 2.3 4.4 1.3]
 [6.1 3.  4.9 1.8]
 [4.8 3.4 1.9 0.2]
 [5.8 2.7 5.1 1.9]
 [4.8 3.  1.4 0.1]
 [6.4 2.9 4.3 1.3]
 [5.2 3.4 1.4 0.2]
 [5.1 3.8 1.5 0.3]
 [6.3 2.5 5.  1.9]
 [6.7 3.3 5.7 2.5]
 [5.8 2.7 5.1 1.9]
 [5.4 3.  4.

In [5]:
total_test=[]
for a,b in zip(iris.data,iris.target):
    total_train.append(a)
    total_test.append(b)
print(type(total_test))

<class 'list'>


In [6]:
classifiers = [
    KNeighborsClassifier(),
    SVC(), 
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    MLPClassifier(max_iter=1000),
    GaussianNB()]
names = ["Nearest Neighbors", "SVM",  
         "Decision Tree", "Random Forest", "Neural Net",
         "Naive Bayes"]

In [7]:


def auc_calculate(clf):
    if hasattr(clf, "decision_function"):
        y_score= clf.fit(X_train, y_train).decision_function(X_test)
    else:
        y_score = clf.fit(X_train, y_train).predict_proba(X_test)[:, 1]
    fpr,tpr,threshold = roc_curve(y_test, y_score) ###计算真正率和假正率
    roc_auc = auc(fpr,tpr) ###计算auc的值
    return [roc_auc,fpr,tpr]



def roc_plt(data): 
    roc_auc=data[0]
    fpr=data[1]
    tpr=data[2]
    plt.figure()
    lw = 2
    plt.figure(figsize=(10,10))
    plt.plot(fpr, tpr, color='darkorange',
             lw=lw, label='ROC curve (area = %0.2f)' % roc_auc) ###假正率为横坐标，真正率为纵坐标做曲线
    plt.plot([0, 1], [0, 1], color='navy', lw=lw, linestyle='--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Receiver operating characteristic example')
    plt.legend(loc="lower right")
    

In [8]:
def accuracy_calculate(clf):
    clf = clf.fit(X_train, y_train)
    num = 0
    for a,b in zip(clf.predict(X_test),y_test):
        if a==b:
            num=num+1
                
    return(num/testing_num)

In [9]:
import time
for name,clf in zip(names, classifiers):
    print(name)
    times = 100
    total=0
    start =time.clock()
    for i in range(times): 
        total = total+accuracy_calculate(clf)
    total = total/times
    end = time.clock()
    print('accuracy: %f' %(total))
    print('Running time: %s Seconds'%(end-start))       

Nearest Neighbors
accuracy: 0.960000
Running time: 0.18647790000068198 Seconds
SVM


C:\Users\Ruiz\anapy\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  
C:\Users\Ruiz\anapy\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Ruiz\anapy\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  


accuracy: 0.980000
Running time: 0.05024489999959769 Seconds
Decision Tree
accuracy: 0.951000
Running time: 0.02642519999972137 Seconds
Random Forest


C:\Users\Ruiz\anapy\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Ruiz\anapy\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  
C:\Users\Ruiz\anapy\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Ruiz\anapy\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  
C:\Users\Ruiz\anapy\

accuracy: 0.976000
Running time: 9.913804899999377 Seconds
Neural Net
accuracy: 0.980000
Running time: 26.378558299998986 Seconds
Naive Bayes
accuracy: 0.980000
Running time: 0.042022999999971944 Seconds


C:\Users\Ruiz\anapy\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  # Remove the CWD from sys.path while we load stuff.
C:\Users\Ruiz\anapy\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  
C:\Users\Ruiz\anapy\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
  # Remove the CWD from sys.path while we load stuff.


In [10]:
type(X_train)

numpy.ndarray

In [12]:
help(roc_curve)

Help on function roc_curve in module sklearn.metrics._ranking:

roc_curve(y_true, y_score, pos_label=None, sample_weight=None, drop_intermediate=True)
    Compute Receiver operating characteristic (ROC)
    
    Note: this implementation is restricted to the binary classification task.
    
    Read more in the :ref:`User Guide <roc_metrics>`.
    
    Parameters
    ----------
    
    y_true : array, shape = [n_samples]
        True binary labels. If labels are not either {-1, 1} or {0, 1}, then
        pos_label should be explicitly given.
    
    y_score : array, shape = [n_samples]
        Target scores, can either be probability estimates of the positive
        class, confidence values, or non-thresholded measure of decisions
        (as returned by "decision_function" on some classifiers).
    
    pos_label : int or str, default=None
        The label of the positive class.
        When ``pos_label=None``, if y_true is in {-1, 1} or {0, 1},
        ``pos_label`` is set to 1, 